---
abstract: 'Simple, correct client for CouchDB'
author:
  - 'Robin Berjon, <robin @t berjon d.t com>'
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CouchDB-Client
no_index:
  directory:
    - inc
    - t
requires:
  Exception::Class: 0
  HTTP::Request: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  URI::Escape: 0
  perl: 5.6
version: 0.01
